name: home_decor
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/44DECODWELL.png
    - assets/images/hero.jpg
    - assets/images/founders.png
    - assets/images/productimage1.jpg

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900

    - family: The Seasons
      fonts:
        - asset: assets/fonts/Fontspring-DEMO-theseasons-reg.otf
        - asset: assets/fonts/Fontspring-DEMO-theseasons-bd.otf
          weight: 700     

    - family: Cinzel
      fonts:
        - asset: assets/fonts/Cinzel-Regular.ttf
        - asset: assets/fonts/Cinzel-SemiBold.ttf
          weight: 700              
